name: cotune_mobile
description: CoTune â€” decentralized music mesh app
version: 0.1.0+1
publish_to: none
environment:
  sdk: ^3.10.7


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  path: ^1.9.1
  permission_handler: ^12.0.1
  easy_file_saver: ^1.1.0
  cupertino_icons: ^1.0.8
  provider: ^6.1.5
  uuid: ^4.5.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  just_audio: ^0.10.5
  audio_session: ^0.2.2
  file_picker: ^10.3.3
  qr_flutter: ^4.1.0
  mobile_scanner: ^7.0.1
  crypto: ^3.0.2
  google_fonts: ^6.3.1
  share_plus: ^12.0.0
  http: ^1.5.0
  protobuf: ^6.0.0
  grpc: ^5.1.0
  intl: ^0.20.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0


flutter:
  uses-material-design: true
  generate: true
